Repository kiali/helm-charts, pull requests merged in 2021-04, with the labels that each got.

#59 set the operator env var to indicate if ad hoc kiali namespaces are allowed
  kiali-operator/templates/deployment.yaml
  kiali-operator/values.yaml
Labels: enhancement, team/saturn

#60 retain the permissions that are still needed for the old supported versions
  kiali-operator/templates/clusterrole.yaml
Labels: team/saturn

#61 Be able to disable ad hoc images.
  kiali-operator/templates/deployment.yaml
  kiali-operator/values.yaml
Labels: team/saturn

#63 Removing HPA permissions
  kiali-operator/templates/clusterrole.yaml
  kiali-server/templates/role-viewer.yaml
  kiali-server/templates/role.yaml
Labels: team/jupiter

#62 audit permissions
  kiali-operator/templates/clusterrole.yaml
  kiali-server/templates/role-viewer.yaml
  kiali-server/templates/role.yaml
Labels: team/saturn

#66 fix the affinity value names
  kiali-server/templates/deployment.yaml
Labels: team/saturn

#67 be able to customize the length of the ansible profile report
  kiali-operator/templates/deployment.yaml
Labels: team/saturn

#69 Add host stanza to Ingress
  kiali-server/templates/ingress.yaml
Labels: team/saturn
